spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sdmes
    username: mesuser
    password: mesuser
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
    show-sql: true

server:
  port: 8080